### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ghost** [JohnTheGr8/YifySharp#1]
Can YifySharp Return(Download) Movie Images/Posters

**Comment by JohnTheGr8** [comment]
Yes, this is possible. You can get image links for movie posters and screenshots. Here's some example code:

``` csharp
var client = new YifyClient();
// Search for Birdman
var searchResults = client.GetMovieList("Birdman").Movies;
// Get the first result
var movieInfo = searchResults[0];
// Get a medium-sized cover image
Console.WriteLine(movieInfo.MediumCoverImage);
```

This will return `https://s.ynet.io/assets/images/movies/birdman_2014/medium-cover.jpg`

You can use `GetMovieDetails` to get more image types and sizes like so:

``` csharp
// Get movie details
var details = client.GetMovieDetails(movieInfo.Id, withImages:true);
// Get a large movie screenshot
Console.WriteLine(details.Images.LargeScreenshotImage1);
```

This will return `https://s.ynet.io/assets/images/movies/birdman_2014/large-screenshot1.jpg`

Hope this helps ;)
